// .cspell.cjs
module.exports = {
  version: "0.2",
  import: ["@cspell/dict-en-au", "@cspell/dict-typescript", "@cspell/dict-node"],
  language: "en-au",
  files: [
    "**/*.{ts,tsx,js,jsx,json,md,yml,yaml}",
    "**/.*.{ts,tsx,js,jsx,json,md,yml,yaml}",
  ],
  ignorePaths: [
    "node_modules",
    "dist",
    "build",
    ".git",
    ".next",
    "out",
    "coverage",
    "public",
    "*.min.js",
    "*.min.css",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "deno.lock",
    ".DS_Store",
    "Thumbs.db",
  ],
  words: [
    // Project specific terms
    "portfolio",
    "card",
    "splitter",
    "mvp",
    "api",
    "auth",
    "bootstrap",
    "invite",
    "accept",
    "login",
    "logout",
    "reset",
    "password",
    "session",
    "member",
    "merchant",
    "transaction",
    "reservation",
    "transfer",
    "payment",
    "pot",
    "tag",
    "ledger",
    "audit",
    "event",
    "stream",
    "sse",

    // Tech terms
    "argon2",
    "argon2i",
    "zod",
    "stdext",
    "PasswordService",
    "hashConfig",
    "hashPassword",
    "verifyPassword",
    "safeParse",
    "drizzle",
    "orm",
    "hono",
    "deno",
    "typescript",
    "tsx",
    "tsconfig",
    "eslint",
    "prettier",
    "vite",
    "webpack",
    "nodejs",
    "jsr",
    "npm",
    "cspell",
    "dict",
    "au",
    "en",
    "pg",
    "postgres",
    "postgresql",
    "uuid",
    "iso",
    "utc",
    "aest",
    "aedt",
    "brisbane",
    "aud",
    "cents",

    // Common developer words
    "config",
    "utils",
    "helpers",
    "constants",
    "types",
    "interfaces",
    "schemas",
    "entities",
    "repositories",
    "services",
    "routes",
    "middleware",
    "handlers",
    "controllers",
    "models",
    "views",
    "components",
    "hooks",
    "utils",
    "lib",
    "src",
    "dist",
    "build",
    "public",
    "assets",
    "styles",
    "css",
    "scss",
    "sass",
    "html",
    "json",
    "yml",
    "yaml",
    "md",
    "txt",
    "gitignore",
    "eslintignore",
    "prettierignore",
    "dockerignore",
    "env",
    "example",
    "template",
    "readme",
    "changelog",
    "license",
    "package",
    "lock",
    "shrinkwrap",
    "tsbuildinfo",
    "dts",
    "map",
    "min",
    "gz",
    "zip",
    "tar",
    "bz2",
    "xz",
  ],
  flagWords: ["TODO", "FIXME", "HACK", "XXX", "NOTE", "BUG"],
  ignoreRegExpList: [
    "/\\/\\/.*", // single-line comments
    "/\\/\\*[\\s\\S]*?\\*\\//", // block comments
    "\\b0x[0-9A-Fa-f]+\\b", // hex literals
    "\\bhttps?:\\/\\/\\S+\\b", // urls
    "\\b[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\\b", // uuids
    "\\b\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z?\\b", // iso dates
    "\\b[A-Z][a-zA-Z0-9]*\\b", // PascalCase identifiers
    "\\b[a-z][a-zA-Z0-9]*\\b", // camelCase identifiers
    "\\b_[a-zA-Z0-9]+\\b", // private identifiers
    "\\b@[a-zA-Z0-9/-]+\\b", // import paths
  ],
  maxNumberOfProblems: 500,
  minWordLength: 3,
  allowCompoundWords: true,
  caseSensitive: false,
  useGitignore: true,
};
